services:
  - type: web
    name: aptify
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
    healthCheckPath: /health
